#!/usr/bin/env bash
tanggalweb=$(TZ=Asia/Jakarta date "+%Y-%m-%d")
tanggalfile=$(TZ=Asia/Jakarta date "+%Y/%m/%d")
filesize=$(du -h $ZIP_NAME)

# Membuat file .md
function md() {
     echo "---" > ${tanggalweb}.md
     echo "name: $ZIP_NAME" >> ${tanggalweb}.md
     echo "date: $tanggalfile" >> ${tanggalweb}.md
     echo "size: $filesize" >> ${tanggalweb}.md
     echo "version: " >> ${tanggalweb}.md
     echo "changelog: " >> ${tanggalweb}.md
     echo "link: " >> ${tanggalweb}.md
     echo "---" >> ${tanggalweb}.md
}

# Kirim File .md
function sendmd() {
	curl -F document=@${tanggalweb}.md "https://api.telegram.org/bot$token/sendDocument" \
			-F chat_id="$chat_id" \
			-F "disable_web_page_preview=true" \
			-F "parse_mode=html"
}
